# Generated by Django 5.1.5 on 2025-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_company', '0002_rename_employee_employeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='it_direction',
            field=models.CharField(max_length=700, verbose_name='Укажите ваше направление в айти'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='linkedin',
            field=models.CharField(max_length=700, verbose_name='Укажите ссылку вашего Linkedin'),
        ),
    ]
