# Generated by Django 5.1.5 on 2025-02-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_company', '0004_employeemodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='message',
        ),
    ]
