# Generated by Django 5.1.5 on 2025-02-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите фотографию')),
                ('title', models.CharField(max_length=100, verbose_name='Введите название книги')),
                ('description', models.TextField(blank=True, verbose_name='Введите краткое описания книги')),
                ('price', models.PositiveIntegerField(default=250, verbose_name='Введите название')),
                ('released_date', models.DateField(verbose_name='Укажите дату выпуска')),
                ('genre', models.CharField(choices=[('ROMANCE', 'ROMANCE'), ('FANTASY', 'FANTASY'), ('CLASSIC', 'CLASSIC'), ('MYSTERY', 'MYSTERY'), ('PHSYCOLOGY', 'PHSYCOLOGY'), ('THRILLER', 'THRILLER')], default='классика', max_length=15, verbose_name='Выберите жанр')),
                ('gmail', models.TextField(blank=True, verbose_name='Введите почту автора')),
                ('author', models.CharField(default='No name', max_length=100, verbose_name='Введите имя автора')),
                ('audi_book', models.URLField(blank=True, verbose_name='укажите ссылку с ютуба')),
            ],
        ),
    ]
