# Generated by Django 5.1.5 on 2025-02-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_options_alter_bookmodel_audi_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('review_text', models.TextField(verbose_name='Оставить отзыв')),
                ('stars', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('book_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.bookmodel')),
            ],
        ),
    ]
