# Generated by Django 5.1.5 on 2025-02-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Введите имя пользователя'),
            preserve_default=False,
        ),
    ]
