# Generated by Django 5.1.5 on 2025-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_review_stars_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='genre',
            field=models.CharField(choices=[('ROMANCE', 'ROMANCE'), ('FANTASY', 'FANTASY'), ('CLASSIC', 'CLASSIC'), ('MYSTERY', 'MYSTERY'), ('PHSYCHOLOGY', 'PHSYCOLOGY'), ('THRILLER', 'THRILLER'), ('DRAMA', 'DRAMA')], default='CLASSIC', max_length=15, verbose_name='Выберите жанр'),
        ),
    ]
