# Generated by Django 5.1.5 on 2025-02-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookmodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.bookmodel'),
        ),
    ]
