# Generated by Django 5.1.5 on 2025-02-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rezkamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='litresmodel',
            name='cover',
            field=models.ImageField(blank=True, default='https://cdn.litres.ru/pub/c/cover_100/71668699.jpg', null=True, upload_to='images/'),
        ),
    ]
