# Generated by Django 5.1.5 on 2025-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_litresmodel_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litresmodel',
            name='cover',
        ),
        migrations.AddField(
            model_name='litresmodel',
            name='author',
            field=models.CharField(blank=True, default='no name', max_length=600, null=True),
        ),
    ]
