# Generated by Django 5.1.5 on 2025-02-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothesmodel',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежды'},
        ),
    ]
