# Generated by Django 5.1.5 on 2025-02-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_alter_bookmodel_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите своё имя')),
                ('address', models.TextField(verbose_name='Введите адрес пункта выдачи')),
                ('gmail', models.EmailField(max_length=254, verbose_name='Введите свой адрес электронной почты')),
                ('product_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='books.bookmodel')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
